# app/mediamtx.py
"""mediamtx integration: YAML config generation, systemd restart, HTTP API client."""
import logging
import subprocess
from typing import Any

import httpx

from app.config import AppConfig

logger = logging.getLogger(__name__)

MEDIAMTX_CONFIG_PATH = "/opt/raspizerocam/mediamtx.yml"
MEDIAMTX_API_BASE = "http://127.0.0.1:9997"
MEDIAMTX_PATH_NAME = "cam"

# Ports served by mediamtx — must match the values written into mediamtx.yml.
RTSP_PORT = 8554
WEBRTC_PORT = 8889
HLS_PORT = 8888


def generate_yaml(config: AppConfig) -> str:
    """Render mediamtx.yml content from AppConfig."""
    hflip = "true" if config.rotation == 180 else "false"
    vflip = "true" if config.rotation == 180 else "false"
    bitrate_bps = config.bitrate_kbps * 1000

    return f"""# Generated by raspizerocam — do not edit manually.
# Regenerated on every PUT /api/config.

logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: :9997

rtsp: yes
rtspAddress: :{RTSP_PORT}

webrtc: yes
webrtcAddress: :{WEBRTC_PORT}

hls: yes
hlsAddress: :{HLS_PORT}

rtmp: no
srt: no

paths:
  {MEDIAMTX_PATH_NAME}:
    source: rpiCamera
    rpiCameraWidth: {config.resolution_width}
    rpiCameraHeight: {config.resolution_height}
    rpiCameraFPS: {config.fps}
    rpiCameraBitrate: {bitrate_bps}
    rpiCameraHFlip: {hflip}
    rpiCameraVFlip: {vflip}
    rpiCameraCodec: h264
"""


def write_yaml(config: AppConfig, path: str = MEDIAMTX_CONFIG_PATH) -> None:
    """Write mediamtx.yml to disk."""
    content = generate_yaml(config)
    with open(path, "w") as f:
        f.write(content)
    logger.info(f"mediamtx.yml written to {path}")


def restart_service() -> bool:
    """Restart the mediamtx systemd service. Returns True on success."""
    try:
        subprocess.run(
            ["systemctl", "restart", "mediamtx"],
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        )
        logger.info("mediamtx service restarted")
        return True
    except subprocess.CalledProcessError as exc:
        logger.error(f"Failed to restart mediamtx: {exc.stderr}")
        return False
    except subprocess.TimeoutExpired:
        logger.error("systemctl restart mediamtx timed out")
        return False


def apply_config(config: AppConfig) -> bool:
    """Write new mediamtx.yml and restart the service."""
    write_yaml(config)
    return restart_service()


def get_path_status(path_name: str = MEDIAMTX_PATH_NAME) -> dict[str, Any] | None:
    """Fetch status of a mediamtx path via its HTTP API.

    Returns None if mediamtx is unreachable or the path doesn't exist.
    """
    try:
        response = httpx.get(
            f"{MEDIAMTX_API_BASE}/v3/paths/get/{path_name}",
            timeout=2.0,
        )
        if response.status_code == 200:
            return response.json()
        return None
    except httpx.HTTPError:
        return None


def get_stream_urls(host: str) -> dict[str, str]:
    """Build the stream URLs that clients can use to connect."""
    return {
        "webrtc": f"http://{host}:{WEBRTC_PORT}/{MEDIAMTX_PATH_NAME}",
        "rtsp": f"rtsp://{host}:{RTSP_PORT}/{MEDIAMTX_PATH_NAME}",
        "hls": f"http://{host}:{HLS_PORT}/{MEDIAMTX_PATH_NAME}/index.m3u8",
    }


def get_stream_state() -> dict[str, Any]:
    """Combined view of mediamtx path state for /api/status."""
    status = get_path_status()
    if status is None:
        return {"camera_running": False, "stream_readers": 0}
    return {
        "camera_running": bool(status.get("ready", False)),
        "stream_readers": len(status.get("readers", [])),
    }
