# app/mediamtx.py
"""mediamtx integration: YAML config generation, systemd restart, HTTP API client."""
import logging
import socket
import subprocess
from typing import Any

import httpx

from app.config import AppConfig

logger = logging.getLogger(__name__)


def _detect_lan_ip() -> str | None:
    """Best-effort discovery of the LAN-facing IPv4 address.

    Uses a UDP socket trick: connecting to a non-routable public IP doesn't
    send any packets but forces the kernel to pick the outgoing interface,
    whose address we can then read. Works even when offline (returns None
    instead of raising).
    """
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.settimeout(0.5)
        sock.connect(("10.255.255.255", 1))
        ip = sock.getsockname()[0]
        sock.close()
        if ip and ip != "127.0.0.1":
            return ip
    except OSError:
        pass
    return None

MEDIAMTX_CONFIG_PATH = "/opt/raspizerocam/mediamtx.yml"
MEDIAMTX_API_BASE = "http://127.0.0.1:9997"
MEDIAMTX_PATH_NAME = "cam"

# Ports served by mediamtx — must match the values written into mediamtx.yml.
RTSP_PORT = 8554
WEBRTC_PORT = 8889
HLS_PORT = 8888


def generate_yaml(config: AppConfig) -> str:
    """Render mediamtx.yml content from AppConfig.

    We explicitly inject the current LAN IP into webrtcAdditionalHosts so that
    mediamtx advertises ICE candidates that the browser can actually reach.
    Without this, v1.9 sometimes picks loopback or docker-bridge addresses and
    WebRTC negotiation fails with 'deadline exceeded while waiting connection'.
    """
    hflip = "true" if config.rotation == 180 else "false"
    vflip = "true" if config.rotation == 180 else "false"
    bitrate_bps = config.bitrate_kbps * 1000

    lan_ip = _detect_lan_ip()
    if lan_ip:
        additional_hosts_line = f"webrtcAdditionalHosts: [{lan_ip}]"
    else:
        additional_hosts_line = "# webrtcAdditionalHosts: []  # LAN IP not detected at generation time"

    return f"""# Generated by raspizerocam — do not edit manually.
# Regenerated on every PUT /api/config.

logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: :9997

rtsp: yes
rtspAddress: :{RTSP_PORT}

webrtc: yes
webrtcAddress: :{WEBRTC_PORT}
{additional_hosts_line}
# TCP fallback bypasses the mDNS host-address obfuscation that Chrome/Firefox
# apply by default. With this set, mediamtx advertises a passive TCP candidate
# that the browser connects to directly — no need for mediamtx to resolve the
# browser's .local candidates back to an IP. Uses the same port number as the
# UDP ICE listener (8189); TCP/UDP namespaces don't conflict.
webrtcLocalTCPAddress: :8890

hls: yes
hlsAddress: :{HLS_PORT}
# Low-Latency HLS: streams partial segments via chunked transfer so hls.js
# can start playback within ~1-2s instead of the 4-6s typical of regular HLS.
hlsVariant: lowLatency

rtmp: no
srt: no

paths:
  {MEDIAMTX_PATH_NAME}:
    source: rpiCamera
    rpiCameraWidth: {config.resolution_width}
    rpiCameraHeight: {config.resolution_height}
    rpiCameraFPS: {config.fps}
    rpiCameraBitrate: {bitrate_bps}
    rpiCameraHFlip: {hflip}
    rpiCameraVFlip: {vflip}
    # Force the 2304x1296 sensor mode (2x2 binning). By default mediamtx picks
    # 1536x864 (3x3 binning) because it's the closest match to the 720p output
    # resolution — but 3x3 binning produces a visibly softer image. 2304x1296
    # is sharper and still runs comfortably at 30fps.
    rpiCameraMode: 2304:1296:10:P
    # Continuous autofocus is the default, but kept explicit for clarity.
    rpiCameraAfMode: continuous
    rpiCameraAfRange: normal
    # I-frame every second (30 frames at 30fps). Default is 60 (= 2s) which
    # adds up to 2s startup/re-sync latency for clients like ExoPlayer that
    # can only start decoding at a keyframe.
    rpiCameraIDRPeriod: {config.fps}
    # Slightly increased sharpness (default 1, range 0-16).
    rpiCameraSharpness: 2
"""
# Note: rpiCameraCodec is omitted — H.264 is the default on mediamtx's primary
# rpiCamera stream and passing an explicit value errors on older versions.


def write_yaml(config: AppConfig, path: str = MEDIAMTX_CONFIG_PATH) -> None:
    """Write mediamtx.yml to disk."""
    content = generate_yaml(config)
    with open(path, "w") as f:
        f.write(content)
    logger.info(f"mediamtx.yml written to {path}")


def restart_service() -> bool:
    """Restart the mediamtx systemd service. Returns True on success."""
    try:
        subprocess.run(
            ["systemctl", "restart", "mediamtx"],
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        )
        logger.info("mediamtx service restarted")
        return True
    except subprocess.CalledProcessError as exc:
        logger.error(f"Failed to restart mediamtx: {exc.stderr}")
        return False
    except subprocess.TimeoutExpired:
        logger.error("systemctl restart mediamtx timed out")
        return False


def apply_config(config: AppConfig) -> bool:
    """Write new mediamtx.yml and restart the service."""
    write_yaml(config)
    return restart_service()


def get_path_status(path_name: str = MEDIAMTX_PATH_NAME) -> dict[str, Any] | None:
    """Fetch status of a mediamtx path via its HTTP API.

    Returns None if mediamtx is unreachable or the path doesn't exist.
    """
    try:
        response = httpx.get(
            f"{MEDIAMTX_API_BASE}/v3/paths/get/{path_name}",
            timeout=2.0,
        )
        if response.status_code == 200:
            return response.json()
        return None
    except httpx.HTTPError:
        return None


def get_stream_urls(host: str) -> dict[str, str]:
    """Build the stream URLs that clients can use to connect.

    The WebRTC player URL uses a trailing slash — mediamtx 301-redirects
    /cam → /cam/ which some iframe implementations don't follow cleanly.
    """
    return {
        "webrtc": f"http://{host}:{WEBRTC_PORT}/{MEDIAMTX_PATH_NAME}/",
        "rtsp": f"rtsp://{host}:{RTSP_PORT}/{MEDIAMTX_PATH_NAME}",
        "hls": f"http://{host}:{HLS_PORT}/{MEDIAMTX_PATH_NAME}/index.m3u8",
    }


def get_stream_state() -> dict[str, Any]:
    """Combined view of mediamtx path state for /api/status."""
    status = get_path_status()
    if status is None:
        return {"camera_running": False, "stream_readers": 0}
    return {
        "camera_running": bool(status.get("ready", False)),
        "stream_readers": len(status.get("readers", [])),
    }
